# Console / Logging
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# C++ support (TFLite Micro)
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_GLIBCXX_LIBCPP=y

# mbedTLS
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ECP_C=y
CONFIG_MBEDTLS_ECDSA_C=y
CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y
CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED=y
CONFIG_MBEDTLS_HEAP_SIZE=16384

# MPU / Userspace
CONFIG_USERSPACE=y
CONFIG_MPU_STACK_GUARD=y
CONFIG_ARM_MPU=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y
# NVS anti-rollback - enable on Day 17
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
# CONFIG_NVS=y
# CONFIG_SETTINGS=y
# CONFIG_SETTINGS_NVS=y
# CONFIG_SETTINGS_NVS_SECTOR_COUNT=2
# CONFIG_SETTINGS_NVS_SECTOR_SIZE_MULT=4
#CONFIG_SETTINGS_NVS_SECTOR_COUNT=2
#CONFIG_SETTINGS_NVS_SECTOR_SIZE_MULT=1

# CRC + Timing
CONFIG_CRC=y
#CONFIG_TIMING_FUNCTIONS=y

# Stack + Heap
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=8192

# Fault protection settings — Day 12:
CONFIG_MBEDTLS_ZEPHYR_ENTROPY=y
CONFIG_HW_STACK_PROTECTION=y
#CONFIG_MBEDTLS_SHA256=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_SHA384=y
CONFIG_MBEDTLS_SHA512=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_RING_BUFFER=y
CONFIG_LOG_PRINTK=y
